#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# ./Allrun.pre

########## the manual part ##########
# restore0Dir
# cp -r 0_org 0

# ccmToFoam mesh_directed-mesh.ccm
# createPatch -overwrite

# setFields
# the "conservative" initialization, but need to switch to OpenFOAM-v2412
# run setAlphaField first, it is very important to avoid "holes"
# setAlphaField 
# funkySetFields -time 0

########## the "core" part ##########
runApplication decomposePar

# runParallel foamRun 
# foamRun -solver incompressibleVoF
mpirun -np 16 foamRun -solver incompressibleVoF -parallel

runApplication reconstructPar

foamPostProcess -solver incompressibleVoF -func yPlus