#!/bin/sh

# Remove the mesh
foamCleanPolyMesh

# Remove time folders
foamListTimes -rm -time 0: -withZero

# Remove logs
rm -rf  gradPOSC.txt log dynamicCode
rm -rf postProcessing
rm -rf processor*
rm log.*
rm force_formatted 
rm force.png

rm -rf 1d_profil
