#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

# ./Allrun.pre

# restore0Dir
cp -r 0_org 0

# ccmToFoam mesh.ccm
# blockMesh

# renumberMesh -noFields -overwrite

# I.C.
funkySetFields -time 0

# exit

# #
# # # # # runApplication $(getApplication)
# #
# # # # # for parallel running:
# runApplication decomposePar

runApplication postProcess

# mpirun --oversubscribe -np 15 rheoInterFoam -parallel
# mpirun --oversubscribe -np 15 interIsoDeboRheoFoam -parallel
# rheoInterFoam
interIsoDeboRheoFoam
#------------------------------------------------------------------------------
